#server:
#  port: 8080
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: employee-service
#          uri: lb://employee-service
#          predicates:
#            - Path=/employee/**
#        - id: department
#          uri: lb://department
#          predicates:
#            - Path=/department/**


server.port=8080
eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka
spring.application.name=ApiGateway
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=department
spring.cloud.gateway.routes[0].uri=http://localhost:8082/department/
spring.cloud.gateway.routes[0].predicates[0]=Path=/department/**